### ISSUE TITLE
ON_DEMAND in 1.8.0 not handling spaces in names?

### ISSUE THREAD

**Issue by terryhonn** [mrlt8/docker-wyze-bridge#498]
Just upgraded to 1.8.0, and noticed that the stream from my Outdoor cam (v1) was no longer available. Log is showing:
```
2022/08/08 16:14:12 [WyzeBridge] 192.168.1.104 - - [08/Aug/2022 16:14:12] "GET /snapshot/garage-doors.jpg HTTP/1.1" 404 -
2022/08/08 16:14:37 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 16:14:37] code 400, message Bad request version ('Doors')
2022/08/08 16:14:37 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 16:14:37] "GET /events/DEMAND/Garage Doors" HTTPStatus.BAD_REQUEST -
2022/08/08 16:14:42 [WyzeBridge] 192.168.1.104 - - [08/Aug/2022 16:14:42] "GET /snapshot/garage-doors.jpg HTTP/1.1" 404 -
2022/08/08 16:14:42 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 16:14:42] code 400, message Bad request version ('Doors')
2022/08/08 16:14:42 [WyzeBridge] 127.0.0.1 - - [08/Aug/2022 16:14:42] "GET /events/DEMAND/Garage Doors" HTTPStatus.BAD_REQUEST -
2022/08/08 16:14:50 [WyzeBridge] 192.168.1.104 - - [08/Aug/2022 16:14:50] "GET /static/loading.svg HTTP/1.1" 304 -
2022/08/08 16:14:50 [WyzeBridge] 192.168.1.104 - - [08/Aug/2022 16:14:50] "GET /static/loading.svg HTTP/1.1" 304 -

```

Maybe that GET call needs escaped? 

Let me know how I can help!

**Comment by mrlt8** [comment]
Ahh thanks for the bug report! None of the cams I testing had any spaces, so I missed this!

**Comment by meyerrj** [comment]
Same issue here, cam's aren't working after the upgrade due to this.

I set ON_DEMAND to false, and even tried setting it to false on the camera specific options.

Is the false setting not being respected properly?

**Comment by DarkBlueProjects** [comment]
I had the exact same issue, I ended up renaming my cameras.

**Comment by dnestico** [comment]
> Same issue here, cam's aren't working after the upgrade due to this.
> 
> I set ON_DEMAND to false, and even tried setting it to false on the camera specific options.
> 
> Is the false setting not being respected properly? 

Same issue for me, set it to false but doesn't seem to be working, now none of my streams are working, I know cameras are fine cuz they online in the Wyze app and they were working fine before this.

**Comment by mrlt8** [comment]
This should be fixed in v1.8.1.

> I set ON_DEMAND to false, and even tried setting it to false on the camera specific options.
> 
> Is the false setting not being respected properly?

Is this an outdoor cam? outdoor cams will be on-demand by default.

**Comment by SkateWarp** [comment]
Fixed for me. :)

**Comment by terryhonn** [comment]
Fixed for me as well! Thanks for your amazing work and responsiveness @mrlt8 !

**Comment by mrlt8** [comment]
FYI, there still seems to be a timing issue with the streams getting closed. #501

**Comment by dnestico** [comment]
@mrlt8 the on-demand option doesn't seem to be respected on my V2's and V3's actually my WCO is filtered out cuz I don't use it anymore.

And hopefully your latest update fixes the streams timing out.

**Comment by mrlt8** [comment]
There was a bug in the HA version that should be fixed in v1.8.2

**Comment by mrlt8** [comment]
@dnestico you should be able to enable the WCO and it will just be on "on-demand" mode until you try to access the stream.

**Comment by dnestico** [comment]
Thank you, I mean like I literally don't use it anymore because I upgraded to all V3s haha, not because of your bridge. 

Also is "on-demand" the state that will show for all cameras when I enable it or will they go to "unavailable" or "idle" when not being watched?

**Comment by mrlt8** [comment]
Not right now, but that is something that would be great to add.

**Comment by dnestico** [comment]
Ah alright. I hope this solves my issue where some cameras just randomly go "unavailable".

Also think I found a bug, I see the little icon that shows they are on demand but my thumbnails are still getting updated in both the webview and my normal dashboard, thought I read in one of the updates it wasn't supposed to do that. I wonder if has to do with the camera card I'm using being set to "auto".

![Uploading Screen Shot 2022-08-09 at 12.48.08 PM.png…]()

<img width="542" alt="Screen Shot 2022-08-09 at 12 46 30 PM" src="https://user-images.githubusercontent.com/3034555/183710033-39d259a5-912a-4011-9165-cfcdaabfcfcb.png">
<img width="546" alt="Screen Shot 2022-08-09 at 12 46 35 PM" src="https://user-images.githubusercontent.com/3034555/183710027-2b720aeb-c86e-4a42-8fd5-e4e99657785c.png">

**Comment by mrlt8** [comment]
Sorry, didn't see your edit. 
Do you have snapshots enabled in your config? The new update just prevents the web view from updating the snapshot - two separate things.

**Comment by dnestico** [comment]
Yes I do have "RTSP:5" enabled, which I thought would be overridden by the on demand setting.

And ah I see then its not a bug! Was just wondering, I like the snapshots updating anyways.
